apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  namespace: k8-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1-container
          image: galdovich95/spring-boot-app:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: HAZELCAST_PATH
              value: "/test"
          volumeMounts:
            - mountPath: /app/data
              name: songs-storage
      volumes:
        - name: songs-storage
          persistentVolumeClaim:
            claimName: songs-pvc
            