apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-deployment
  namespace: k8-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2-container
          image: galdovich95/spring-boot-app:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8081"
            - name: HAZELCAST_PATH
              value: "/test2"
