apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-app.labels.currentDate" . | nindent 4 }}
    {{- include "my-app.labels.version" . | nindent 4 }}
data:
  CONFIG_VALUE: "fromConfigMap"