apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SECRET_VALUE: ZnJvbVNlY3JldA==  # fromSecret
  POSTGRES_NAME: cG9zdGdyZXM=     # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM= # postgres
