apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}