apiVersion: v1
kind: PersistentVolume
metadata:
  name: db1-storage
  namespace: k8-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/db1-0
    type: DirectoryOrCreate
