apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db2
  namespace: k8-app
spec:
  serviceName: "db2"
  replicas: 1
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
      labels:
        app: db2
    spec:
      containers:
        - name: db2-container
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db2-storage
  volumeClaimTemplates:
    - metadata:
        name: db2-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: hostpath
